# Site Settings
title: My Resume
url: 'http://zacharysells.github.io'
baseurl: ''

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Zachary Sells
tagline: DevOps/Software Engineer
location: San Diego, CA
pic: profile.png 
summary: "I started my career as a software engineer developing python APIs. \
Our small team had the need to deploy our application publicly on the cloud. \
That's when I got into the DevOps/CloudOps space. \
<br>
<br>
Today my main areas of expertise are in AWS and Kubernetes. I help manage  \
dozens of environment's built on these technologies. We use ansible for \
deployments and Terraform for environment provisioning. \
<br>
<br>
Because of my background in software development, I am also proficient in Python and Docker."

#sidebar links
email: zacharysells@gmail.com
phone: 626 242 3802
website: zacharysells.github.io
upwork:
  id: _~01d20b6030f8f9a8a0
  display: Upwork profile

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
